/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author Alejandra García Preciado - 252444
 */
public class CalculoMaterialesConcretoForm extends javax.swing.JFrame {
    
    /**
     * Referencia al coordinador de aplicación. Permite la navegación entre los
     * distintos formularios del sistema.
     */
    private CoordinadorAplicacion coordinador;

    /**
     * Referencia al coordinador de negocio. Proporciona acceso a la lógica de
     * negocio para la gestión de cálculo de materiales.
     */
    private CoordinadorNegocio coordinadorNegocio;

    /**
     * Creates new form CalculoMaterialesForm
     */
    public CalculoMaterialesConcretoForm() {
        initComponents();
        this.coordinador = CoordinadorAplicacion.getInstancia();
        this.coordinadorNegocio = CoordinadorNegocio.getInstancia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanelProporciones = new javax.swing.JPanel();
        lblProporciones = new javax.swing.JLabel();
        lblPorcionCemento = new javax.swing.JLabel();
        lblPorcionArena = new javax.swing.JLabel();
        lblPorcionGrava = new javax.swing.JLabel();
        nombreEmpresa = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnDescargarPDF = new javax.swing.JButton();
        jPanelResultados = new javax.swing.JPanel();
        lblCemento = new javax.swing.JLabel();
        lblVolumenElemento = new javax.swing.JLabel();
        lblTipoElemento = new javax.swing.JLabel();
        lblResistencia = new javax.swing.JLabel();
        lblArena = new javax.swing.JLabel();
        lblAgua = new javax.swing.JLabel();
        lblResultados = new javax.swing.JLabel();
        lblGrava = new javax.swing.JLabel();
        lblNota = new javax.swing.JLabel();
        campoTipoElemento = new javax.swing.JTextField();
        campoVolumenElemento = new javax.swing.JTextField();
        campoCementoRequerido = new javax.swing.JTextField();
        campoAgua = new javax.swing.JTextField();
        campoArena = new javax.swing.JTextField();
        campoGrava = new javax.swing.JTextField();
        lblCampoResistencia = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(231, 246, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanelProporciones.setBackground(new java.awt.Color(231, 246, 255));

        lblProporciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblProporciones.setForeground(new java.awt.Color(6, 108, 169));
        lblProporciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProporciones.setText("Proporciones por volumen");

        lblPorcionCemento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPorcionCemento.setForeground(new java.awt.Color(0, 0, 0));
        lblPorcionCemento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPorcionCemento.setText("Por 1 porción de cemento.");

        lblPorcionArena.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPorcionArena.setForeground(new java.awt.Color(0, 0, 0));
        lblPorcionArena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPorcionArena.setText("Usar 1.6 porción de arena.");

        lblPorcionGrava.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPorcionGrava.setForeground(new java.awt.Color(0, 0, 0));
        lblPorcionGrava.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPorcionGrava.setText("Usar 1.8 porción de grava.");

        javax.swing.GroupLayout jPanelProporcionesLayout = new javax.swing.GroupLayout(jPanelProporciones);
        jPanelProporciones.setLayout(jPanelProporcionesLayout);
        jPanelProporcionesLayout.setHorizontalGroup(
            jPanelProporcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProporcionesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelProporcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPorcionCemento, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProporciones, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelProporcionesLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelProporcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPorcionArena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPorcionGrava, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelProporcionesLayout.setVerticalGroup(
            jPanelProporcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProporcionesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblProporciones)
                .addGap(18, 18, 18)
                .addComponent(lblPorcionCemento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPorcionArena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPorcionGrava)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        nombreEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        nombreEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        nombreEmpresa.setText("BuildControl");

        btnVolver.setBackground(new java.awt.Color(95, 168, 211));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver a inicio");
        btnVolver.setBorderPainted(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnDescargarPDF.setBackground(new java.awt.Color(95, 168, 211));
        btnDescargarPDF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDescargarPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnDescargarPDF.setText("Descargar PDF");
        btnDescargarPDF.setBorderPainted(false);
        btnDescargarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarPDFActionPerformed(evt);
            }
        });

        jPanelResultados.setBackground(new java.awt.Color(231, 246, 255));

        lblCemento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCemento.setForeground(new java.awt.Color(0, 0, 0));
        lblCemento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCemento.setText("Cemento requerido:");

        lblVolumenElemento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblVolumenElemento.setForeground(new java.awt.Color(0, 0, 0));
        lblVolumenElemento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVolumenElemento.setText("Volumen del elemento:");

        lblTipoElemento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTipoElemento.setForeground(new java.awt.Color(0, 0, 0));
        lblTipoElemento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipoElemento.setText("Tipo de elemento:");

        lblResistencia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblResistencia.setForeground(new java.awt.Color(0, 0, 0));
        lblResistencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblResistencia.setText("Resistencia (por default):");

        lblArena.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblArena.setForeground(new java.awt.Color(0, 0, 0));
        lblArena.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblArena.setText("Arena:");

        lblAgua.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAgua.setForeground(new java.awt.Color(0, 0, 0));
        lblAgua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAgua.setText("Agua:");

        lblResultados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblResultados.setForeground(new java.awt.Color(6, 108, 169));
        lblResultados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultados.setText("Resultados material peso seco");

        lblGrava.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblGrava.setForeground(new java.awt.Color(0, 0, 0));
        lblGrava.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGrava.setText("Grava:");

        lblNota.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNota.setForeground(new java.awt.Color(6, 108, 169));
        lblNota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNota.setText("Nota: Las cantidades no incluyen el porcentaje de desperdicio.");

        campoTipoElemento.setEditable(false);
        campoTipoElemento.setBackground(new java.awt.Color(231, 246, 255));
        campoTipoElemento.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        campoTipoElemento.setForeground(new java.awt.Color(0, 0, 0));
        campoTipoElemento.setBorder(null);

        campoVolumenElemento.setEditable(false);
        campoVolumenElemento.setBackground(new java.awt.Color(231, 246, 255));
        campoVolumenElemento.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        campoVolumenElemento.setForeground(new java.awt.Color(0, 0, 0));
        campoVolumenElemento.setBorder(null);

        campoCementoRequerido.setEditable(false);
        campoCementoRequerido.setBackground(new java.awt.Color(231, 246, 255));
        campoCementoRequerido.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        campoCementoRequerido.setForeground(new java.awt.Color(0, 0, 0));
        campoCementoRequerido.setBorder(null);

        campoAgua.setEditable(false);
        campoAgua.setBackground(new java.awt.Color(231, 246, 255));
        campoAgua.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        campoAgua.setForeground(new java.awt.Color(0, 0, 0));
        campoAgua.setBorder(null);

        campoArena.setEditable(false);
        campoArena.setBackground(new java.awt.Color(231, 246, 255));
        campoArena.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        campoArena.setForeground(new java.awt.Color(0, 0, 0));
        campoArena.setBorder(null);

        campoGrava.setEditable(false);
        campoGrava.setBackground(new java.awt.Color(231, 246, 255));
        campoGrava.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        campoGrava.setForeground(new java.awt.Color(0, 0, 0));
        campoGrava.setBorder(null);

        lblCampoResistencia.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCampoResistencia.setForeground(new java.awt.Color(0, 0, 0));
        lblCampoResistencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCampoResistencia.setText("3000 psi / 210 kg / cm2 / 21 MPa");

        javax.swing.GroupLayout jPanelResultadosLayout = new javax.swing.GroupLayout(jPanelResultados);
        jPanelResultados.setLayout(jPanelResultadosLayout);
        jPanelResultadosLayout.setHorizontalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelResultadosLayout.createSequentialGroup()
                        .addComponent(lblResistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCampoResistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelResultadosLayout.createSequentialGroup()
                        .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                                .addComponent(lblCemento, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCementoRequerido, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                                .addComponent(lblVolumenElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoVolumenElemento))
                            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                                .addComponent(lblTipoElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTipoElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                                .addComponent(lblAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoAgua))
                            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblGrava, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(lblArena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoArena, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoGrava, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        jPanelResultadosLayout.setVerticalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultadosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblResultados)
                .addGap(18, 18, 18)
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoElemento)
                    .addComponent(campoTipoElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVolumenElemento)
                    .addComponent(campoVolumenElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResistencia)
                    .addComponent(lblCampoResistencia))
                .addGap(10, 10, 10)
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCemento)
                    .addComponent(campoCementoRequerido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgua)
                    .addComponent(campoAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArena)
                    .addComponent(campoArena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrava)
                    .addComponent(campoGrava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblNota)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGap(506, 506, 506)
                        .addComponent(btnDescargarPDF))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(jPanelProporciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(nombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(nombreEmpresa)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDescargarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jPanelProporciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed

    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnDescargarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarPDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDescargarPDFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescargarPDF;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField campoAgua;
    private javax.swing.JTextField campoArena;
    private javax.swing.JTextField campoCementoRequerido;
    private javax.swing.JTextField campoGrava;
    private javax.swing.JTextField campoTipoElemento;
    private javax.swing.JTextField campoVolumenElemento;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelProporciones;
    private javax.swing.JPanel jPanelResultados;
    private javax.swing.JLabel lblAgua;
    private javax.swing.JLabel lblArena;
    private javax.swing.JLabel lblCampoResistencia;
    private javax.swing.JLabel lblCemento;
    private javax.swing.JLabel lblGrava;
    private javax.swing.JLabel lblNota;
    private javax.swing.JLabel lblPorcionArena;
    private javax.swing.JLabel lblPorcionCemento;
    private javax.swing.JLabel lblPorcionGrava;
    private javax.swing.JLabel lblProporciones;
    private javax.swing.JLabel lblResistencia;
    private javax.swing.JLabel lblResultados;
    private javax.swing.JLabel lblTipoElemento;
    private javax.swing.JLabel lblVolumenElemento;
    private javax.swing.JLabel nombreEmpresa;
    // End of variables declaration//GEN-END:variables
}
